
name: java-cap-btp-deploy
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: sudo apt install openjdk-17-jdk openjdk-17-jre

      - run: update-alternatives --config java
      - run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/bin/java" >> ~/.bashrc
      - run: source ~/.bashrc

      - run: java --version

      - run: echo ${JAVA_HOME}
      - run: mvn -version

      - run: java --version

      - run: echo ${JAVA_HOME}

      - run: yes | sudo apt install maven
      - run: mvn -version


      - run: npm install -g @sap/cds-dk
      - run: npm install -g mbt
      - run: wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
      - run: echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - run: sudo apt-get update
      - run: sudo apt-get install cf8-cli
      - run: cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
      - run: yes | cf install-plugin multiapps
      - run: cds add hana --for production
      - run: cds add xsuaa --for production
      - run: cds add mta
      - run: cds add approuter --for production
      - run: cds build --production
      - run: mbt build -t gen --mtar mta.tar
      - run: cf deploy gen/mta.tar

