
name: java-cap-btp-deploy
inputs:
  api-url:
    description: 'BTP API URL'
    required: true
  username:
    description: 'BTP Username'
    required: true
  password:
    description: 'BTP Password'
    required: true
  org:
    description: 'BTP Org'
    required: true
  space:
    description: 'BTP Space'
    required: true
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - run: echo $JAVA_HOME
      - run: echo mvn -version

      - run: npm install -g @sap/cds-dk
      - run: npm install -g mbt
      - run: wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
      - run: echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - run: sudo apt-get update
      - run: sudo apt-get install cf8-cli
      - run: cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
      - run: yes | cf install-plugin multiapps
      - run: cds add hana --for production
      - run: cds add xsuaa --for production
      - run: cds add mta
      - run: cds add approuter --for production
      - run: cds build --production
      - run: mbt build -t gen --mtar mta.tar
      - run: cf login -a INPUT_API_URL -u INPUT_USERNAME -p INPUT_PASSWORD -o INPUT_ORG -s INPUT_SPACE
      - run: cf deploy gen/mta.tar

