
name: java-cap-btp-deploy
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - run: sudo bash
      - run: sudo apt-get update
      - run: sudo apt-get install -y --no-install-recommends ca-certificates gnupg2 
      - run: rm -rf /var/lib/apt/lists/*

      - run: export GNUPGHOME="$(mktemp -d)"
      - run: gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys CACB9FE09150307D1D22D82962754C3B3ABCFE23
      - run: gpg --batch --export --armor 'CACB 9FE0 9150 307D 1D22 D829 6275 4C3B 3ABC FE23' > /etc/apt/trusted.gpg.d/sapmachine.gpg.asc
      - run: gpgconf --kill all && rm -rf "$GNUPGHOME"
      - run: echo "deb http://dist.sapmachine.io/debian/$(dpkg --print-architecture)/ ./" > /etc/apt/sources.list.d/sapmachine.list
      - run: sudo apt-get update
      - run: sudo apt-get -y --no-install-recommends install sapmachine-17-jdk
      - run: rm -rf /var/lib/apt/lists/*
      - run: export JAVA_HOME=/usr/lib/jvm/sapmachine-17

      - run: yes | sudo apt install maven
      - run: npm install -g @sap/cds-dk
      - run: npm install -g mbt
      - run: wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
      - run: echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - run: sudo apt-get update
      - run: sudo apt-get install cf8-cli
      - run: cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
      - run: yes | cf install-plugin multiapps
      - run: cds add hana --for production
      - run: cds add xsuaa --for production
      - run: cds add mta
      - run: cds add approuter --for production
      - run: cds build --production
      - run: mbt build -t gen --mtar mta.tar
      - run: cf deploy gen/mta.tar

